<script>
    function createFolder()
    {
        console.log("Entered the Create Folder");
        <?php

            $folderName = "kobaja";
                /*$allData[0]["lastname"];*/
            if( !file_exists($mediaPath.'/'.$folderName)){
                mkdir($mediaPath.'/'.$folderName, 0775);
            }
        ?>
        console.log("Sent Into Function!");
    }
</script>

<input type="button" value="Create a Folder" onclick="createFolder()">

<div id="all_canvas" style="height: auto; width: 100%; position: absolute">
    <div class="images" id="images" class="column"; style="height: 400px; width: 50%; position: absolute;">
        <div class="image_canvas" id="image_canvas" class="column" style="height: 100%; width: 100%;">
        </div>
        <div class="video_container" id="video_container" class="column" style="display: none; width: 100%; height: 300px;">
            <video id="video_canvas" controls width="100%" height="100%" src="" onplay="hideOverlay()" onpause="showOverlay()">
            </video>
        </div>
        <div class="image_small_canvas" id="image_small_canvas" class="column" style="height: 100%; width: 100%; position: relative">
    </div>
    </div>
</div>


<!-- Skripta za obradu slika -->

<script type="text/javascript">
    //ispisivanje slika
    function printImages(b, i, count) {
        var path, img, disp;
        var numberOfImages = count;
        path = b;

        //prva slika proslijedjena biti će veća
        if(i == 0){
            disp = document.getElementById('image_canvas');
            disp.style.overflow = 'hidden';
            img = document.createElement('img');

            img.id = i;
            img.src = path;
            img.onload = function() {
                setImageSize(img, "prvi");
            }
        }
        //sve ostale, ukljucujuci i prvu, prikazuju se manje

        disp = document.getElementById('image_small_canvas');
        img = document.createElement('img');

        img.style.width = '40px';
        img.style.height = '40px';
        img.style.objectFit = 'cover';
        img.style.paddingTop = '0.5%';
        img.style.paddingRight = '0.25%';
        img.style.paddingLeft = '0.25';
        img.style.paddingBottom = '0%';
        img.style.position = 'relative';

        img.id = ++i;
        img.src = path;
        img.onclick = function(){
            changeMain(0, img.id);
        }
        img.onmouseenter = function () {
            img.style.opacity = '0.4';
        }
        img.onmouseout = function () {
            img.style.opacity = '1';
        }
        disp.appendChild(img);
    }

    //funkcija za dodavanje videa
    function addVideo(b, i) {
        var path, vid, disp;
        path = b;
        if(i == 0){
            disp = document.getElementById('image_canvas');
            vid = document.createElement('video');

            vid.type = "video/mp4";
            vid.src = path;
            vid.id = i;
            disp.appendChild(vid);
        }

        disp = document.getElementById('image_small_canvas');
        vid = document.createElement('video');
        disp.style.overflow = 'hidden';

        vid.style.width = '40px';
        vid.style.height = '40px';
        vid.style.objectFit = 'fill';
        vid.style.overflow = 'hidden';
        vid.style.paddingTop = '0.5%';
        vid.style.paddingRight = '0.25%';
        vid.style.paddingLeft = '0.25';
        vid.style.paddingBottom = '0%';
        vid.style.position = 'relative';

        vid.id = ++i;
        vid.type = "video/mp4";
        vid.src = path;

        vid.onclick = function(){
            changeMain(0, vid.id);
        }
        vid.onmouseenter = function () {
            vid.style.opacity = '0.4';
        }
        vid.onmouseout = function () {
            vid.style.opacity = '1';
        }

        disp.appendChild(vid);

    }


    //funkcija za mijenjanje slike koja se trenutno prikazuje (velike slike)
    function changeMain(idm, id2){
        var im1 = document.getElementById(idm);
        var temp;
        var im2 = document.getElementById(id2);

        //zamjena ako se trenutno prikazuje slika a zelimo prikazati video, zato sto nije moguce mijenjati tip div-a
        if(im2.type == 'video/mp4' && im1.type != 'video/mp4'){
            //im1.id = im2.id;
            im1.id = 'hiddenimg';
            im1 = document.getElementById("image_canvas");
            im1.style.display = 'none';
            temp = document.getElementById("video_container");
            temp.style.display = 'inline';
            temp = document.getElementById("overlay_large");
            temp.style.visibility = 'visible';

            im1 = document.getElementById("image_small_canvas");
            if(im1.style.marginTop != '0px'){
                im1.style.marginTop = '0px';
            }

            im1 = document.getElementById('video_canvas');
            im1.type = 'video/mp4';
            im1.src = im2.src;
            im1.id = 0;

            console.log("changed source to: " + im1.src + "and the new id is: " + im1.id);

            //zamjena ako se trenutno prikazuje video a zelimo prikazati sliku, zato sto nije moguce mijenjati tip div-a
        }else if(im1.type == 'video/mp4' && im2.type != 'video/mp4'){
            console.log("is the else if working");
            im1.id = 'video_canvas';
            im1 = document.getElementById("video_container");
            im1.style.display = 'none';

            im1 = document.getElementById("image_canvas");


            var krp = document.getElementById("image_small_canvas");

            im1 = document.getElementById("image_canvas");

            im1.style.display = 'inline';
            im1.style.position = 'absolute';
            im1.style.height = '100%';

            var two = im1.offsetHeight;

            krp.style.marginTop = two + 'px';
            im1.style.width = '100%';

            var img = document.getElementById("hiddenimg");
            img.src = im2.src;
            img.id = 0;

            img.onload = function() {
                setImageSize(img, 0);
            }

        }
        else{
            console.log("nijedan uvjet nije ispunjen");
            im1.src = im2.src;
            im1.id = 0;
            setImageSize(im1, "nije");
        }
    }

    //postavljanje slike da se centrira u div
    function setImageSize(ima,  ch){
        ima.id = 0;
        var div = document.getElementById("image_canvas");
        var x, y, x1, y1, ratio, ratio1, sizechan, margin;

        x = ima.naturalWidth;
        y = ima.naturalHeight;
        x1 = div.offsetWidth;
        y1 = div.offsetHeight;

        ratio = x/y;
        ratio1 = x1/y1;

        //treba se provjeriti dal moraju ici navodnici oko vrijednosti dok se postavljaju ili ne, i mogu li se te vrijednosti opće mijenjati
        //treba posloziti da se slike i centriraju prema parent divu!
        if(ratio > ratio1){
            sizechan = x1/x;
            ima.style.width = x1 + 'px';
            ima.style.height = (sizechan * y) + 1 + 'px';

            y = sizechan * y;
            margin = (100 - (y/y1 * 100)) / 2;

            ima.marginTop = margin + '%';
            ima.marginBottom = margin + '%';

        } else if (ratio < ratio1){
            sizechan = y1/y;
            ima.style.height = y1 + 'px';
            ima.style.width = (sizechan * x) + 1 + 'px';

            x = sizechan * x;
            margin = (100 - (x/x1 * 100)) / 2;

            ima.style.marginLeft = margin + '%';
            ima.marginRight = margin + '%';
        }else{
            ima.style.width = x1;
            ima.style.height = y1;
        }
        if(ch == "prvi"){
            div.appendChild(ima);
        }
    }

    //automatsko mijenjanje slika
    function displayNextImage(num, numberOfImages) {
        if(num+1 < numberOfImages){
            num++;
        }else {
            num = num%numberOfImages;
            num++;
        }
        console.log("3 sec has passed " + num);
        changeMain(0, num);
        //changeMain()
    }
    /*
    function displayPreviousImage() {
        x = (x <= 0) ? images.length - 1 : x - 1;
        document.getElementById("img").src = images[x];
    }
    */

    function startTimer(numberOfImages) {
        i=1;
        //setInterval(function(){ displayNextImage(i++, numberOfImages); }, 1000);
    }


</script>


<!-- php za dobivanje elemenata od servera, pita se prvo trenutni link u magento arhitekturi, koji je otvoreni, zatim prema tome linku, se u serverovoj arhitekturi trazi folder u kojem
se izlistaju svi potrebni nazivi fileova, nakon toga se u magentu listaju svi podaci uz pomoć vrijednosti iz servera-->

<?php

//stvarni link trenutnog foldera
$actual_link = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

//Pulling the last part of the URL, which will be the vendor name!

$getpath = explode("/",$actual_link);
$extensionOfCurrentVendor = end($getpath);
$extensionOfCurrentVendor = str_replace(".html","",$extensionOfCurrentVendor);

//za zadnju verziju potrebno je zakomentirati jedan od ovih
//$actual_link = dirname($actual_link);
$actual_link = dirname($actual_link);
$actual_link = dirname($actual_link);
$actual_link = $actual_link . "/images";

//prvi dio ce uvijek biti isti, no nakon pub/media/ treba ubaciti zeljeni link, dakle, ako se sprema prema imenu vendora, iz databasea uzmemo ime vendora i ubacimo u
// "pub/media" . $extensionOfCurrentVendor sve ostalo ostaje isto

$fullPath = realpath(dirname(__FILE__) . "/images/" . $extensionOfCurrentVendor);
$files = glob($fullPath . '/*.*');
 
//PROVJERA
//echo "<br>" . count($files) . "<br>";

for ($i=0; $i<count($files); $i++)
{
    $sending_link = "";
    $image = $files[$i];
    $supported_file = array(
        'gif',
        'jpg',
        'jpeg',
        'png'
    );
    $supported_file2 = array(
        'mp4',
        'ogg'
    );

    $ext = strtolower(pathinfo($image, PATHINFO_EXTENSION));
    if (in_array($ext, $supported_file)) {
        
        // show only image name if you want to show full path then use this code // echo $image."<br />";
        $sending_link = $actual_link . "/" . $extensionOfCurrentVendor . "/" . basename($image);
        //echo  "We are sending this to function" . $actual_link . "<br>";
        echo '<script type="text/javascript">','printImages(' .  '"' . $sending_link . '"' . ', ' . $i .  ', ' . count($files) . ');','</script>';
    } else if(in_array($ext, $supported_file2)){
        $sending_link = $actual_link . "/" . basename($image);
        echo '<script type="text/javascript">','addVideo(' .  '"' . $sending_link . '"' . ', ' . $i . ');','</script>';
    } else{
        continue;
    }
}
?>

<br><br><br><br><br><br><br><br>
<div style="height: 500px"></div>
